server:
  port: 9090
spring:
  application:
    name: user-service
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: public
  datasource:
    driver-class-name: org.postgresql.Driver
    username: lorem
    password: change_me
    url: jdbc:postgresql://localhost:5432/postgres
springdoc:
  api-docs:
    path: /api-docs.yaml
  swagger-ui:
    path: /swagger-ui.html